### ISSUE TITLE
Can't edit the website

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tina-starter-alpaca#86]
Can't edit the site not more in production, not being able to create a fork (which already exists).

Given I'm on https://tina-starter-alpaca.now.sh/docs/getting-started
When i click Edit this site
Then I get errors

```
https://tina-starter-alpaca.now.sh/api/proxy-github HTTP 500
Error: next-tinacms-github: the apiProxy was created without a signing key
```

<img width="1356" alt="Capture d’écran 2020-08-19 à 13 21 32" src="https://user-images.githubusercontent.com/103008/90629164-2cb2cb80-e21f-11ea-987d-9442a6c35733.png">

Note: the UI is wrong, we don't catch the HTTP 500 error right away and let people think it's a fork/public issue when it's not.

/cc @jhuggett

**Comment by DirtyF** [comment]
All we need to do is add a Signing Key in Vercel here?

**Comment by jhuggett** [comment]
> All we need to do is add a Signing Key in Vercel here?

Yep, I think that should fix it

**Comment by DirtyF** [comment]
@jhuggett Added the same key used in the .env in Vercel and still happening, should we force a new deploy?

**Comment by Basovs** [comment]
> @jhuggett Added the same key used in the `.env` in Vercel and still happening, had to redeploy.
> 
> Thanks.

CONFIRM FIX - 2020-12-30 - Yes you HAVE TO redeploy after u have added the SIGNIN_KEY from .env to vercel. Thanks!
